import os

env = Environment()

debug = ARGUMENTS.get("debug", 0)

if env["PLATFORM"] == "win32":
    env.Append(CCFLAGS = ["/EHsc", "/W3"])
    if int(debug):
        env.Append(CCFLAGS = ["/Zi", "/Od", "/MDd"],
                   LINKFLAGS = ["/DEBUG"])
    else:
        env.Append(CCFLAGS = ["/O2", "/MD"])
    modulesdir = "" # FIXME
else:
    env.Append(CCFLAGS = ["-Wall", "-pipe", "-I.."])
    if int(debug):
        env.Append(CCFLAGS = ["-g"])
    else:
        env.Append(CCFLAGS = ["-O2"])
    if env["PLATFORM"] == "darwin":
        env.Append(CPPDEFINES = ["DARWIN", "SIGPROCMASK_SETS_THREAD_MASK"],
                   SHLINKFLAGS = "-undefined dynamic_lookup")
        modulesdir = "/usr/libexec/apache2"
    else:
        modulesdir = "" # FIXME

echo = env.SharedLibrary(target = "mod_websocket_echo.so", source=["echo.c"],
                         SHLIBPREFIX="",
                         SHLIBSUFFIX=".so")

env.Install(dir=modulesdir, source=echo)

# Install

env.Alias("install", modulesdir)
